# Generated by Django 4.2.11 on 2024-06-12 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media_app', '0003_alter_comment_user_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to='./Social_Media_app/Images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'pdf'])]),
        ),
    ]
