# Generated by Django 4.2.11 on 2024-06-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media_app', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='./Social_Media_app/Images'),
        ),
    ]
