# Generated by Django 4.2.11 on 2024-06-12 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media_app', '0007_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like', related_query_name='post_like', to='Social_Media_app.post'),
        ),
    ]
