# Generated by Django 4.2.11 on 2024-06-24 05:09

import Social_Media_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media_app', '0008_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[Social_Media_app.models.validate_brainvire_mail], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='./Social_Media_app/Images', validators=[Social_Media_app.models.validate_image]),
        ),
    ]
